# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
-jobs:
  include:
    - os: linux
      dist: focal
    - os: osx
      osx_image: xcode12.2
